name: pre-commit
on:
  pull_request:
    branches:
      - main
jobs:
  backend-pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dev Container CLI
        uses: devcontainers/ci@v0.3
      - name: Start devcontainer
        run: devcontainer up --workspace-folder .
      - name: Run pre-commit in devcontainer
        run: devcontainer exec --workspace-folder . pre-commit run
