name: unit-test
on:
  pull_request:
    branches:
      - main
jobs:
  backend-unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dev Container CLI
        uses: devcontainers/ci@v0.3
      - name: Start devcontainer
        run: devcontainer up --workspace-folder .
      - name: Run backend unit tests
        run: |
          devcontainer exec --workspace-folder . coverage run --source=backend -m pytest backend/tests/unit_tests
          devcontainer exec --workspace-folder . coverage xml -o backend-coverage.xml
          devcontainer exec --workspace-folder . coverage report -m
      - name: Upload backend coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: backend-coverage.xml
          fail_ci_if_error: true
          flags: backend-unit-tests
          token: ${{ secrets.CODECOV_TOKEN }}
  frontend-unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dev Container CLI
        uses: devcontainers/ci@v0.3
      - name: Start devcontainer
        run: devcontainer up --workspace-folder .
      - name: Run frontend unit tests
        run: |
          devcontainer exec --workspace-folder . xvfb-run -a coverage run --source=frontend -m pytest frontend/tests
          devcontainer exec --workspace-folder . coverage xml -o frontend-coverage.xml
          devcontainer exec --workspace-folder . coverage report -m
      - name: Upload frontend coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: frontend-coverage.xml
          fail_ci_if_error: true
          flags: frontend-unit-tests
          token: ${{ secrets.CODECOV_TOKEN }}
